config:
  debugMode: false
  selectedGameVersion: '23_2_2'
  alwaysOnTop: false
  showActiveSectionScore: false
  showActiveSectionDifference: false
  lastSectionAnchored: true
  showSongProgressBar: true
  hideTotalScore: false
  showAnimations: true
  enableAutoscroll: true
  disableHardwareAcceleration: false
  styleChosen: defaultLight